// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class HomeWorkTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void () {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/");
    driver.FindElement(By.CssSelector(".btn-outline-white")).Click();
    driver.FindElement(By.CssSelector(".btn-link:nth-child(1)")).Click();
    driver.FindElement(By.Id("signupName")).Click();
    driver.FindElement(By.Id("signupName")).SendKeys("Ivan");
    driver.FindElement(By.Id("signupLastName")).Click();
    driver.FindElement(By.Id("signupLastName")).SendKeys("Zadunaylo");
    driver.FindElement(By.Id("signupEmail")).Click();
    driver.FindElement(By.Id("signupEmail")).SendKeys("zadulivan123@gmail.com");
    driver.FindElement(By.Id("signupPassword")).Click();
    driver.FindElement(By.Id("signupPassword")).SendKeys("1234567Qwe");
    driver.FindElement(By.Id("signupRepeatPassword")).Click();
    driver.FindElement(By.Id("signupRepeatPassword")).SendKeys("1234567Qwe");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
    driver.FindElement(By.Id("userNavDropdown")).Click();
    driver.FindElement(By.CssSelector(".dropdown-item:nth-child(6)")).Click();
  }
  [Test]
  public void () {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/");
    driver.FindElement(By.CssSelector(".btn-outline-white")).Click();
    driver.FindElement(By.Id("signinEmail")).Click();
    driver.FindElement(By.Id("signinEmail")).SendKeys("zadulivan123@gmail.com");
    driver.FindElement(By.Id("signinPassword")).Click();
    driver.FindElement(By.Id("signinPassword")).SendKeys("1234567Qwe");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(2)")).Click();
    driver.FindElement(By.LinkText("Profile")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".close")).Click();
    driver.FindElement(By.Id("userNavDropdown")).Click();
    driver.FindElement(By.CssSelector(".dropdown-item:nth-child(6)")).Click();
  }
  [Test]
  public void () {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/");
    driver.FindElement(By.CssSelector(".btn-outline-white")).Click();
    driver.FindElement(By.Id("signinEmail")).Click();
    driver.FindElement(By.Id("signinEmail")).SendKeys("zadulivan123@gmail.com");
    driver.FindElement(By.Id("signinPassword")).Click();
    driver.FindElement(By.Id("signinPassword")).SendKeys("1234567Qwe");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.Id("addCarBrand")).Click();
    {
      var dropdown = driver.FindElement(By.Id("addCarBrand"));
      dropdown.FindElement(By.XPath("//option[. = 'Audi']")).Click();
    }
    driver.FindElement(By.Id("addCarMileage")).Click();
    driver.FindElement(By.Id("addCarMileage")).SendKeys("238");
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.Id("userNavDropdown")).Click();
    driver.FindElement(By.CssSelector(".dropdown-item:nth-child(6)")).Click();
  }
  [Test]
  public void () {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/");
    driver.FindElement(By.CssSelector(".btn-outline-white")).Click();
    driver.FindElement(By.Id("signinEmail")).Click();
    driver.FindElement(By.Id("signinEmail")).SendKeys("zadulivan123@gmail.com");
    driver.FindElement(By.Id("signinPassword")).Click();
    driver.FindElement(By.Id("signinPassword")).SendKeys("1234567Qwe");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".car_add-expense")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("239");
    driver.FindElement(By.Id("addExpenseLiters")).Click();
    driver.FindElement(By.Id("addExpenseLiters")).SendKeys("1");
    driver.FindElement(By.Id("addExpenseTotalCost")).Click();
    driver.FindElement(By.Id("addExpenseTotalCost")).SendKeys("12");
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.Id("userNavDropdown")).Click();
    driver.FindElement(By.CssSelector(".dropdown-item:nth-child(6)")).Click();
  }
  [Test]
  public void () {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/");
    driver.FindElement(By.CssSelector(".btn-outline-white")).Click();
    driver.FindElement(By.Id("signinEmail")).Click();
    driver.FindElement(By.Id("signinEmail")).SendKeys("zadulivan123@gmail.com");
    driver.FindElement(By.Id("signinPassword")).Click();
    driver.FindElement(By.Id("signinPassword")).SendKeys("1234567Qwe");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(2)")).Click();
    driver.FindElement(By.Id("userNavDropdown")).Click();
    driver.FindElement(By.LinkText("Settings")).Click();
    driver.FindElement(By.CssSelector(".btn-danger-bg")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
  }
}
